package com.quxin.freshfun.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.NON_NULL)
public class Activity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.gmt_create
     *
     * @mbggenerated
     */
    private Integer gmt_create;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.gmt_modified
     *
     * @mbggenerated
     */
    private Integer gmt_modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_des
     *
     * @mbggenerated
     */
    private String activity_des;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_img
     *
     * @mbggenerated
     */
    private String activity_img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_info_img
     *
     * @mbggenerated
     */
    private String activity_info_img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_content
     *
     * @mbggenerated
     */
    private String activity_content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.activity_info_content
     *
     * @mbggenerated
     */
    private String activity_info_content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.is_deleted
     *
     * @mbggenerated
     */
    private Byte is_deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.id
     *
     * @return the value of activity.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.id
     *
     * @param id the value for activity.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.gmt_create
     *
     * @return the value of activity.gmt_create
     *
     * @mbggenerated
     */
    public Integer getGmt_create() {
        return gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.gmt_create
     *
     * @param gmt_create the value for activity.gmt_create
     *
     * @mbggenerated
     */
    public void setGmt_create(Integer gmt_create) {
        this.gmt_create = gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.gmt_modified
     *
     * @return the value of activity.gmt_modified
     *
     * @mbggenerated
     */
    public Integer getGmt_modified() {
        return gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.gmt_modified
     *
     * @param gmt_modified the value for activity.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmt_modified(Integer gmt_modified) {
        this.gmt_modified = gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_des
     *
     * @return the value of activity.activity_des
     *
     * @mbggenerated
     */
    public String getActivity_des() {
        return activity_des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_des
     *
     * @param activity_des the value for activity.activity_des
     *
     * @mbggenerated
     */
    public void setActivity_des(String activity_des) {
        this.activity_des = activity_des == null ? null : activity_des.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_img
     *
     * @return the value of activity.activity_img
     *
     * @mbggenerated
     */
    public String getActivity_img() {
        return activity_img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_img
     *
     * @param activity_img the value for activity.activity_img
     *
     * @mbggenerated
     */
    public void setActivity_img(String activity_img) {
        this.activity_img = activity_img == null ? null : activity_img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_info_img
     *
     * @return the value of activity.activity_info_img
     *
     * @mbggenerated
     */
    public String getActivity_info_img() {
        return activity_info_img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_info_img
     *
     * @param activity_info_img the value for activity.activity_info_img
     *
     * @mbggenerated
     */
    public void setActivity_info_img(String activity_info_img) {
        this.activity_info_img = activity_info_img == null ? null : activity_info_img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_content
     *
     * @return the value of activity.activity_content
     *
     * @mbggenerated
     */
    public String getActivity_content() {
        return activity_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_content
     *
     * @param activity_content the value for activity.activity_content
     *
     * @mbggenerated
     */
    public void setActivity_content(String activity_content) {
        this.activity_content = activity_content == null ? null : activity_content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.activity_info_content
     *
     * @return the value of activity.activity_info_content
     *
     * @mbggenerated
     */
    public String getActivity_info_content() {
        return activity_info_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.activity_info_content
     *
     * @param activity_info_content the value for activity.activity_info_content
     *
     * @mbggenerated
     */
    public void setActivity_info_content(String activity_info_content) {
        this.activity_info_content = activity_info_content == null ? null : activity_info_content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.is_deleted
     *
     * @return the value of activity.is_deleted
     *
     * @mbggenerated
     */
    public Byte getIs_deleted() {
        return is_deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.is_deleted
     *
     * @param is_deleted the value for activity.is_deleted
     *
     * @mbggenerated
     */
    public void setIs_deleted(Byte is_deleted) {
        this.is_deleted = is_deleted;
    }
}