package com.quxin.freshfun.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.NON_NULL)
public class GoodsDeliveryTimesPOJO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_delivery_times.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_delivery_times.gmt_create
     *
     * @mbggenerated
     */
    private Long gmt_create;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_delivery_times.gmt_modified
     *
     * @mbggenerated
     */
    private Long gmt_modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_delivery_times.goods_id
     *
     * @mbggenerated
     */
    private Integer goods_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_delivery_times.type_id
     *
     * @mbggenerated
     */
    private Integer type_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_delivery_times.delivery_times
     *
     * @mbggenerated
     */
    private Integer delivery_times;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_delivery_times.reseved_field
     *
     * @mbggenerated
     */
    private String reseved_field;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_delivery_times.id
     *
     * @return the value of goods_delivery_times.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_delivery_times.id
     *
     * @param id the value for goods_delivery_times.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_delivery_times.gmt_create
     *
     * @return the value of goods_delivery_times.gmt_create
     *
     * @mbggenerated
     */
    public Long getGmt_create() {
        return gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_delivery_times.gmt_create
     *
     * @param gmt_create the value for goods_delivery_times.gmt_create
     *
     * @mbggenerated
     */
    public void setGmt_create(Long gmt_create) {
        this.gmt_create = gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_delivery_times.gmt_modified
     *
     * @return the value of goods_delivery_times.gmt_modified
     *
     * @mbggenerated
     */
    public Long getGmt_modified() {
        return gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_delivery_times.gmt_modified
     *
     * @param gmt_modified the value for goods_delivery_times.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmt_modified(Long gmt_modified) {
        this.gmt_modified = gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_delivery_times.goods_id
     *
     * @return the value of goods_delivery_times.goods_id
     *
     * @mbggenerated
     */
    public Integer getGoods_id() {
        return goods_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_delivery_times.goods_id
     *
     * @param goods_id the value for goods_delivery_times.goods_id
     *
     * @mbggenerated
     */
    public void setGoods_id(Integer goods_id) {
        this.goods_id = goods_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_delivery_times.type_id
     *
     * @return the value of goods_delivery_times.type_id
     *
     * @mbggenerated
     */
    public Integer getType_id() {
        return type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_delivery_times.type_id
     *
     * @param type_id the value for goods_delivery_times.type_id
     *
     * @mbggenerated
     */
    public void setType_id(Integer type_id) {
        this.type_id = type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_delivery_times.delivery_times
     *
     * @return the value of goods_delivery_times.delivery_times
     *
     * @mbggenerated
     */
    public Integer getDelivery_times() {
        return delivery_times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_delivery_times.delivery_times
     *
     * @param delivery_times the value for goods_delivery_times.delivery_times
     *
     * @mbggenerated
     */
    public void setDelivery_times(Integer delivery_times) {
        this.delivery_times = delivery_times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_delivery_times.reseved_field
     *
     * @return the value of goods_delivery_times.reseved_field
     *
     * @mbggenerated
     */
    public String getReseved_field() {
        return reseved_field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_delivery_times.reseved_field
     *
     * @param reseved_field the value for goods_delivery_times.reseved_field
     *
     * @mbggenerated
     */
    public void setReseved_field(String reseved_field) {
        this.reseved_field = reseved_field == null ? null : reseved_field.trim();
    }
}