package com.quxin.freshfun.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.NON_NULL)
public class GoodsSelectionPOJO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_selection.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_selection.goods_id
     *
     * @mbggenerated
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_selection.image_url
     *
     * @mbggenerated
     */
    private String imageUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_selection.gmt_creat
     *
     * @mbggenerated
     */
    private Long gmtCreat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_selection.gmt_modified
     *
     * @mbggenerated
     */
    private Long gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_selection.id
     *
     * @return the value of goods_selection.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_selection.id
     *
     * @param id the value for goods_selection.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_selection.goods_id
     *
     * @return the value of goods_selection.goods_id
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_selection.goods_id
     *
     * @param goodsId the value for goods_selection.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_selection.image_url
     *
     * @return the value of goods_selection.image_url
     *
     * @mbggenerated
     */
    public String getImageUrl() {
        return imageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_selection.image_url
     *
     * @param imageUrl the value for goods_selection.image_url
     *
     * @mbggenerated
     */
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl == null ? null : imageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_selection.gmt_creat
     *
     * @return the value of goods_selection.gmt_creat
     *
     * @mbggenerated
     */
    public Long getGmtCreat() {
        return gmtCreat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_selection.gmt_creat
     *
     * @param gmtCreat the value for goods_selection.gmt_creat
     *
     * @mbggenerated
     */
    public void setGmtCreat(Long gmtCreat) {
        this.gmtCreat = gmtCreat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_selection.gmt_modified
     *
     * @return the value of goods_selection.gmt_modified
     *
     * @mbggenerated
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_selection.gmt_modified
     *
     * @param gmtModified the value for goods_selection.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }
}