package com.quxin.freshfun.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.NON_NULL)
public class GoodsStorePOJO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_store.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_store.gmt_create
     *
     * @mbggenerated
     */
    private Long gmt_create;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_store.gmt_modified
     *
     * @mbggenerated
     */
    private Long gmt_modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_store.store_name
     *
     * @mbggenerated
     */
    private String store_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_store.store_mobile
     *
     * @mbggenerated
     */
    private String store_mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_store.store_address
     *
     * @mbggenerated
     */
    private String store_address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_store.reserved_field
     *
     * @mbggenerated
     */
    private String reserved_field;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_store.id
     *
     * @return the value of goods_store.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_store.id
     *
     * @param id the value for goods_store.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_store.gmt_create
     *
     * @return the value of goods_store.gmt_create
     *
     * @mbggenerated
     */
    public Long getGmt_create() {
        return gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_store.gmt_create
     *
     * @param gmt_create the value for goods_store.gmt_create
     *
     * @mbggenerated
     */
    public void setGmt_create(Long gmt_create) {
        this.gmt_create = gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_store.gmt_modified
     *
     * @return the value of goods_store.gmt_modified
     *
     * @mbggenerated
     */
    public Long getGmt_modified() {
        return gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_store.gmt_modified
     *
     * @param gmt_modified the value for goods_store.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmt_modified(Long gmt_modified) {
        this.gmt_modified = gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_store.store_name
     *
     * @return the value of goods_store.store_name
     *
     * @mbggenerated
     */
    public String getStore_name() {
        return store_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_store.store_name
     *
     * @param store_name the value for goods_store.store_name
     *
     * @mbggenerated
     */
    public void setStore_name(String store_name) {
        this.store_name = store_name == null ? null : store_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_store.store_mobile
     *
     * @return the value of goods_store.store_mobile
     *
     * @mbggenerated
     */
    public String getStore_mobile() {
        return store_mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_store.store_mobile
     *
     * @param store_mobile the value for goods_store.store_mobile
     *
     * @mbggenerated
     */
    public void setStore_mobile(String store_mobile) {
        this.store_mobile = store_mobile == null ? null : store_mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_store.store_address
     *
     * @return the value of goods_store.store_address
     *
     * @mbggenerated
     */
    public String getStore_address() {
        return store_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_store.store_address
     *
     * @param store_address the value for goods_store.store_address
     *
     * @mbggenerated
     */
    public void setStore_address(String store_address) {
        this.store_address = store_address == null ? null : store_address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_store.reserved_field
     *
     * @return the value of goods_store.reserved_field
     *
     * @mbggenerated
     */
    public String getReserved_field() {
        return reserved_field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_store.reserved_field
     *
     * @param reserved_field the value for goods_store.reserved_field
     *
     * @mbggenerated
     */
    public void setReserved_field(String reserved_field) {
        this.reserved_field = reserved_field == null ? null : reserved_field.trim();
    }
}