package com.quxin.freshfun.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.NON_NULL)
public class GoodsPOJO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.gmt_create
     *
     * @mbggenerated
     */
    private Long gmt_create;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.gmt_modified
     *
     * @mbggenerated
     */
    private Long gmt_modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_name
     *
     * @mbggenerated
     */
    private String goods_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_des
     *
     * @mbggenerated
     */
    private String goods_des;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_img
     *
     * @mbggenerated
     */
    private String goods_img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_type
     *
     * @mbggenerated
     */
    private String goods_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.shop_price
     *
     * @mbggenerated
     */
    private Integer shop_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.market_price
     *
     * @mbggenerated
     */
    private Integer market_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.store_id
     *
     * @mbggenerated
     */
    private Long store_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_weight
     *
     * @mbggenerated
     */
    private Integer goods_weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.goods_storage
     *
     * @mbggenerated
     */
    private Integer goods_storage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.warnning
     *
     * @mbggenerated
     */
    private Byte warnning;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.is_on_sale
     *
     * @mbggenerated
     */
    private Byte is_on_sale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.is_new
     *
     * @mbggenerated
     */
    private Byte is_new;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.is_hot
     *
     * @mbggenerated
     */
    private Byte is_hot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.is_promote
     *
     * @mbggenerated
     */
    private Byte is_promote;

    private Long merchant_proxy_id;


    private String goodsMoney;

    private String marketMoney;

    private Integer merchantProxyId;

    public Integer getMerchantProxyId() {
        return merchantProxyId;
    }

    public void setMerchantProxyId(Integer merchantProxyId) {
        this.merchantProxyId = merchantProxyId;
    }

    public Integer getAgencyFees() {
        return agencyFees;
    }

    public void setAgencyFees(Integer agencyFees) {
        this.agencyFees = agencyFees;
    }

    public Integer getSales() {
        return sales;
    }

    public void setSales(Integer sales) {
        this.sales = sales;
    }

    public Double getSalesMoney() {
        return SalesMoney;
    }

    public void setSalesMoney(Double salesMoney) {
        SalesMoney = salesMoney;
    }

    private Integer agencyFees;

    private Integer sales;

    private Double SalesMoney;

    public String getGoodsDetailImg() {
        return goodsDetailImg;
    }

    public void setGoodsDetailImg(String goodsDetailImg) {
        this.goodsDetailImg = goodsDetailImg;
    }

    private String goodsDetailImg;

    public String getMarketMoney() {
        return marketMoney;
    }

    public void setMarketMoney(String marketMoney) {
        this.marketMoney = marketMoney;
    }

    public String getGoodsMoney() {
        return goodsMoney;
    }

    public void setGoodsMoney(String goodsMoney) {
        this.goodsMoney = goodsMoney;
    }

    public Long getMerchant_proxy_id() {
        return merchant_proxy_id;
    }

    public void setMerchant_proxy_id(Long merchant_proxy_id) {
        this.merchant_proxy_id = merchant_proxy_id;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.reserved_field
     *
     * @mbggenerated
     */
    private String reserved_field;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.id
     *
     * @return the value of goods.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.id
     *
     * @param id the value for goods.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.gmt_create
     *
     * @return the value of goods.gmt_create
     *
     * @mbggenerated
     */
    public Long getGmt_create() {
        return gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.gmt_create
     *
     * @param gmt_create the value for goods.gmt_create
     *
     * @mbggenerated
     */
    public void setGmt_create(Long gmt_create) {
        this.gmt_create = gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.gmt_modified
     *
     * @return the value of goods.gmt_modified
     *
     * @mbggenerated
     */
    public Long getGmt_modified() {
        return gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.gmt_modified
     *
     * @param gmt_modified the value for goods.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmt_modified(Long gmt_modified) {
        this.gmt_modified = gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_name
     *
     * @return the value of goods.goods_name
     *
     * @mbggenerated
     */
    public String getGoods_name() {
        return goods_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_name
     *
     * @param goods_name the value for goods.goods_name
     *
     * @mbggenerated
     */
    public void setGoods_name(String goods_name) {
        this.goods_name = goods_name == null ? null : goods_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_des
     *
     * @return the value of goods.goods_des
     *
     * @mbggenerated
     */
    public String getGoods_des() {
        return goods_des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_des
     *
     * @param goods_des the value for goods.goods_des
     *
     * @mbggenerated
     */
    public void setGoods_des(String goods_des) {
        this.goods_des = goods_des == null ? null : goods_des.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_img
     *
     * @return the value of goods.goods_img
     *
     * @mbggenerated
     */
    public String getGoods_img() {
        return goods_img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_img
     *
     * @param goods_img the value for goods.goods_img
     *
     * @mbggenerated
     */
    public void setGoods_img(String goods_img) {
        this.goods_img = goods_img == null ? null : goods_img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_type
     *
     * @return the value of goods.goods_type
     *
     * @mbggenerated
     */
    public String getGoods_type() {
        return goods_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_type
     *
     * @param goods_type the value for goods.goods_type
     *
     * @mbggenerated
     */
    public void setGoods_type(String goods_type) {
        this.goods_type = goods_type == null ? null : goods_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.shop_price
     *
     * @return the value of goods.shop_price
     *
     * @mbggenerated
     */
    public Integer getShop_price() {
        return shop_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.shop_price
     *
     * @param shop_price the value for goods.shop_price
     *
     * @mbggenerated
     */
    public void setShop_price(Integer shop_price) {
        this.shop_price = shop_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.market_price
     *
     * @return the value of goods.market_price
     *
     * @mbggenerated
     */
    public Integer getMarket_price() {
        return market_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.market_price
     *
     * @param market_price the value for goods.market_price
     *
     * @mbggenerated
     */
    public void setMarket_price(Integer market_price) {
        this.market_price = market_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.store_id
     *
     * @return the value of goods.store_id
     *
     * @mbggenerated
     */
    public Long getStore_id() {
        return store_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.store_id
     *
     * @param store_id the value for goods.store_id
     *
     * @mbggenerated
     */
    public void setStore_id(Long store_id) {
        this.store_id = store_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_weight
     *
     * @return the value of goods.goods_weight
     *
     * @mbggenerated
     */
    public Integer getGoods_weight() {
        return goods_weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_weight
     *
     * @param goods_weight the value for goods.goods_weight
     *
     * @mbggenerated
     */
    public void setGoods_weight(Integer goods_weight) {
        this.goods_weight = goods_weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.goods_storage
     *
     * @return the value of goods.goods_storage
     *
     * @mbggenerated
     */
    public Integer getGoods_storage() {
        return goods_storage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.goods_storage
     *
     * @param goods_storage the value for goods.goods_storage
     *
     * @mbggenerated
     */
    public void setGoods_storage(Integer goods_storage) {
        this.goods_storage = goods_storage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.warnning
     *
     * @return the value of goods.warnning
     *
     * @mbggenerated
     */
    public Byte getWarnning() {
        return warnning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.warnning
     *
     * @param warnning the value for goods.warnning
     *
     * @mbggenerated
     */
    public void setWarnning(Byte warnning) {
        this.warnning = warnning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.is_on_sale
     *
     * @return the value of goods.is_on_sale
     *
     * @mbggenerated
     */
    public Byte getIs_on_sale() {
        return is_on_sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.is_on_sale
     *
     * @param is_on_sale the value for goods.is_on_sale
     *
     * @mbggenerated
     */
    public void setIs_on_sale(Byte is_on_sale) {
        this.is_on_sale = is_on_sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.is_new
     *
     * @return the value of goods.is_new
     *
     * @mbggenerated
     */
    public Byte getIs_new() {
        return is_new;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.is_new
     *
     * @param is_new the value for goods.is_new
     *
     * @mbggenerated
     */
    public void setIs_new(Byte is_new) {
        this.is_new = is_new;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.is_hot
     *
     * @return the value of goods.is_hot
     *
     * @mbggenerated
     */
    public Byte getIs_hot() {
        return is_hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.is_hot
     *
     * @param is_hot the value for goods.is_hot
     *
     * @mbggenerated
     */
    public void setIs_hot(Byte is_hot) {
        this.is_hot = is_hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.is_promote
     *
     * @return the value of goods.is_promote
     *
     * @mbggenerated
     */
    public Byte getIs_promote() {
        return is_promote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.is_promote
     *
     * @param is_promote the value for goods.is_promote
     *
     * @mbggenerated
     */
    public void setIs_promote(Byte is_promote) {
        this.is_promote = is_promote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods.reserved_field
     *
     * @return the value of goods.reserved_field
     *
     * @mbggenerated
     */
    public String getReserved_field() {
        return reserved_field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods.reserved_field
     *
     * @param reserved_field the value for goods.reserved_field
     *
     * @mbggenerated
     */
    public void setReserved_field(String reserved_field) {
        this.reserved_field = reserved_field == null ? null : reserved_field.trim();
    }

    @Override
    public String toString() {
        return "GoodsPOJO [id=" + id + ", gmt_create=" + gmt_create
                + ", gmt_modified=" + gmt_modified + ", goods_name="
                + goods_name + ", goods_des=" + goods_des + ", goods_img="
                + goods_img + ", goods_type=" + goods_type + ", shop_price="
                + shop_price + ", market_price=" + market_price + ", store_id="
                + store_id + ", goods_weight=" + goods_weight
                + ", goods_storage=" + goods_storage + ", warnning=" + warnning
                + ", is_on_sale=" + is_on_sale + ", is_new=" + is_new
                + ", is_hot=" + is_hot + ", is_promote=" + is_promote
                + ", merchant_proxy_id=" + merchant_proxy_id + ", goodsMoney="
                + goodsMoney + ", marketMoney=" + marketMoney
                + ", reserved_field=" + reserved_field + "]";
    }



}