package com.quxin.freshfun.model;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.NON_NULL)
public class GoodsTypePOJO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_type.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_type.gmt_create
     *
     * @mbggenerated
     */
    private Long gmt_create;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_type.gmt_modified
     *
     * @mbggenerated
     */
    private Long gmt_modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_type.goods_type
     *
     * @mbggenerated
     */
    private String goods_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_type.goods_type_img
     *
     * @mbggenerated
     */
    private String goods_type_img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_type.is_deleted
     *
     * @mbggenerated
     */
    private Byte is_deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_type.reserved_field
     *
     * @mbggenerated
     */
    private String reserved_field;
    
    private List<GtypeVsGid> typeGids;
    
    private String goodsInfoDes;
    
    public String getGoodsInfoDes() {
		return goodsInfoDes;
	}

	public void setGoodsInfoDes(String goodsInfoDes) {
		this.goodsInfoDes = goodsInfoDes;
	}

	public String getGoodsInfoImg() {
		return goodsInfoImg;
	}

	public void setGoodsInfoImg(String goodsInfoImg) {
		this.goodsInfoImg = goodsInfoImg;
	}

	private String goodsInfoImg;

	public List<GtypeVsGid> getTypeGids() {
		return typeGids;
	}

	public void setTypeGids(List<GtypeVsGid> typeGids) {
		this.typeGids = typeGids;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_type.id
     *
     * @return the value of goods_type.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_type.id
     *
     * @param id the value for goods_type.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_type.gmt_create
     *
     * @return the value of goods_type.gmt_create
     *
     * @mbggenerated
     */
    public Long getGmt_create() {
        return gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_type.gmt_create
     *
     * @param gmt_create the value for goods_type.gmt_create
     *
     * @mbggenerated
     */
    public void setGmt_create(Long gmt_create) {
        this.gmt_create = gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_type.gmt_modified
     *
     * @return the value of goods_type.gmt_modified
     *
     * @mbggenerated
     */
    public Long getGmt_modified() {
        return gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_type.gmt_modified
     *
     * @param gmt_modified the value for goods_type.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmt_modified(Long gmt_modified) {
        this.gmt_modified = gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_type.goods_type
     *
     * @return the value of goods_type.goods_type
     *
     * @mbggenerated
     */
    public String getGoods_type() {
        return goods_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_type.goods_type
     *
     * @param goods_type the value for goods_type.goods_type
     *
     * @mbggenerated
     */
    public void setGoods_type(String goods_type) {
        this.goods_type = goods_type == null ? null : goods_type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_type.goods_type_img
     *
     * @return the value of goods_type.goods_type_img
     *
     * @mbggenerated
     */
    public String getGoods_type_img() {
        return goods_type_img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_type.goods_type_img
     *
     * @param goods_type_img the value for goods_type.goods_type_img
     *
     * @mbggenerated
     */
    public void setGoods_type_img(String goods_type_img) {
        this.goods_type_img = goods_type_img == null ? null : goods_type_img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_type.is_deleted
     *
     * @return the value of goods_type.is_deleted
     *
     * @mbggenerated
     */
    public Byte getIs_deleted() {
        return is_deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_type.is_deleted
     *
     * @param is_deleted the value for goods_type.is_deleted
     *
     * @mbggenerated
     */
    public void setIs_deleted(Byte is_deleted) {
        this.is_deleted = is_deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_type.reserved_field
     *
     * @return the value of goods_type.reserved_field
     *
     * @mbggenerated
     */
    public String getReserved_field() {
        return reserved_field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_type.reserved_field
     *
     * @param reserved_field the value for goods_type.reserved_field
     *
     * @mbggenerated
     */
    public void setReserved_field(String reserved_field) {
        this.reserved_field = reserved_field == null ? null : reserved_field.trim();
    }

	@Override
	public String toString() {
		return "GoodsTypePOJO [id=" + id + ", gmt_create=" + gmt_create
				+ ", gmt_modified=" + gmt_modified + ", goods_type="
				+ goods_type + ", goods_type_img=" + goods_type_img
				+ ", is_deleted=" + is_deleted + ", reserved_field="
				+ reserved_field + ", typeGids=" + typeGids + ", goodsInfoDes="
				+ goodsInfoDes + ", goodsInfoImg=" + goodsInfoImg + "]";
	}
    
}