package com.quxin.freshfun.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.NON_NULL)
public class GoodsDeliveryTypePOJO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_delivery_type.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_delivery_type.gmt_create
     *
     * @mbggenerated
     */
    private Long gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_delivery_type.gmt_modified
     *
     * @mbggenerated
     */
    private Long gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_delivery_type.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_delivery_type.frequency
     *
     * @mbggenerated
     */
    private Integer frequency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_delivery_type.reserved_field
     *
     * @mbggenerated
     */
    private Byte deliveryCount;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Long getGmtCreate() {
        return gmtCreate;
    }

    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    public Long getGmtModified() {
        return gmtModified;
    }

    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getFrequency() {
        return frequency;
    }

    public void setFrequency(Integer frequency) {
        this.frequency = frequency;
    }

    public Byte getDeliveryCount() {
        return deliveryCount;
    }

    public void setDeliveryCount(Byte deliveryCount) {
        this.deliveryCount = deliveryCount;
    }
}