package com.quxin.freshfun.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.NON_NULL)
public class GoodsLimit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_limit.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_limit.gmt_create
     *
     * @mbggenerated
     */
    private Long gmt_create;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_limit.gmt_modified
     *
     * @mbggenerated
     */
    private Long gmt_modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_limit.start_time
     *
     * @mbggenerated
     */
    private Long start_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_limit.end_time
     *
     * @mbggenerated
     */
    private Long end_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_limit.market_price
     *
     * @mbggenerated
     */
    private Integer market_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_limit.shop_price
     *
     * @mbggenerated
     */
    private Integer shop_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_limit.goods_name
     *
     * @mbggenerated
     */
    private String goods_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_limit.goods_des
     *
     * @mbggenerated
     */
    private String goods_des;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_limit.goods_img
     *
     * @mbggenerated
     */
    private String goods_img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_limit.goods_storage
     *
     * @mbggenerated
     */
    private Integer goods_storage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_limit.is_on_sale
     *
     * @mbggenerated
     */
    private Integer is_on_sale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_limit.store_id
     *
     * @mbggenerated
     */
    private Integer store_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_limit.merchant_proxy_id
     *
     * @mbggenerated
     */
    private Integer merchant_proxy_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_limit.reserved_field
     *
     * @mbggenerated
     */
    private Integer limit_count;
    
    private Byte is_promote;
    
    public Integer getLimit_count() {
		return limit_count;
	}

	public void setLimit_count(Integer limit_count) {
		this.limit_count = limit_count;
	}

	public Byte getIs_promote() {
		return is_promote;
	}

	public void setIs_promote(Byte is_promote) {
		this.is_promote = is_promote;
	}

    private String goodsMoney;
    
    private String marketMoney;
    
    public String getMarketMoney() {
		return marketMoney;
	}

	public void setMarketMoney(String marketMoney) {
		this.marketMoney = marketMoney;
	}

	public String getGoodsMoney() {
		return goodsMoney;
	}

	public void setGoodsMoney(String goodsMoney) {
		this.goodsMoney = goodsMoney;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods.reserved_field
     *
     * @mbggenerated
     */
    private Long time;

    public Long getTime() {
		return time;
	}

	public void setTime(Long time) {
		this.time = time;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_limit.id
     *
     * @return the value of goods_limit.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_limit.id
     *
     * @param id the value for goods_limit.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_limit.gmt_create
     *
     * @return the value of goods_limit.gmt_create
     *
     * @mbggenerated
     */
    public Long getGmt_create() {
        return gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_limit.gmt_create
     *
     * @param gmt_create the value for goods_limit.gmt_create
     *
     * @mbggenerated
     */
    public void setGmt_create(Long gmt_create) {
        this.gmt_create = gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_limit.gmt_modified
     *
     * @return the value of goods_limit.gmt_modified
     *
     * @mbggenerated
     */
    public Long getGmt_modified() {
        return gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_limit.gmt_modified
     *
     * @param gmt_modified the value for goods_limit.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmt_modified(Long gmt_modified) {
        this.gmt_modified = gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_limit.start_time
     *
     * @return the value of goods_limit.start_time
     *
     * @mbggenerated
     */
    public Long getStart_time() {
        return start_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_limit.start_time
     *
     * @param start_time the value for goods_limit.start_time
     *
     * @mbggenerated
     */
    public void setStart_time(Long start_time) {
        this.start_time = start_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_limit.end_time
     *
     * @return the value of goods_limit.end_time
     *
     * @mbggenerated
     */
    public Long getEnd_time() {
        return end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_limit.end_time
     *
     * @param end_time the value for goods_limit.end_time
     *
     * @mbggenerated
     */
    public void setEnd_time(Long end_time) {
        this.end_time = end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_limit.market_price
     *
     * @return the value of goods_limit.market_price
     *
     * @mbggenerated
     */
    public Integer getMarket_price() {
        return market_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_limit.market_price
     *
     * @param market_price the value for goods_limit.market_price
     *
     * @mbggenerated
     */
    public void setMarket_price(Integer market_price) {
        this.market_price = market_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_limit.shop_price
     *
     * @return the value of goods_limit.shop_price
     *
     * @mbggenerated
     */
    public Integer getShop_price() {
        return shop_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_limit.shop_price
     *
     * @param shop_price the value for goods_limit.shop_price
     *
     * @mbggenerated
     */
    public void setShop_price(Integer shop_price) {
        this.shop_price = shop_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_limit.goods_name
     *
     * @return the value of goods_limit.goods_name
     *
     * @mbggenerated
     */
    public String getGoods_name() {
        return goods_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_limit.goods_name
     *
     * @param goods_name the value for goods_limit.goods_name
     *
     * @mbggenerated
     */
    public void setGoods_name(String goods_name) {
        this.goods_name = goods_name == null ? null : goods_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_limit.goods_des
     *
     * @return the value of goods_limit.goods_des
     *
     * @mbggenerated
     */
    public String getGoods_des() {
        return goods_des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_limit.goods_des
     *
     * @param goods_des the value for goods_limit.goods_des
     *
     * @mbggenerated
     */
    public void setGoods_des(String goods_des) {
        this.goods_des = goods_des == null ? null : goods_des.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_limit.goods_img
     *
     * @return the value of goods_limit.goods_img
     *
     * @mbggenerated
     */
    public String getGoods_img() {
        return goods_img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_limit.goods_img
     *
     * @param goods_img the value for goods_limit.goods_img
     *
     * @mbggenerated
     */
    public void setGoods_img(String goods_img) {
        this.goods_img = goods_img == null ? null : goods_img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_limit.goods_storage
     *
     * @return the value of goods_limit.goods_storage
     *
     * @mbggenerated
     */
    public Integer getGoods_storage() {
        return goods_storage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_limit.goods_storage
     *
     * @param goods_storage the value for goods_limit.goods_storage
     *
     * @mbggenerated
     */
    public void setGoods_storage(Integer goods_storage) {
        this.goods_storage = goods_storage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_limit.is_on_sale
     *
     * @return the value of goods_limit.is_on_sale
     *
     * @mbggenerated
     */
    public Integer getIs_on_sale() {
        return is_on_sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_limit.is_on_sale
     *
     * @param is_on_sale the value for goods_limit.is_on_sale
     *
     * @mbggenerated
     */
    public void setIs_on_sale(Integer is_on_sale) {
        this.is_on_sale = is_on_sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_limit.store_id
     *
     * @return the value of goods_limit.store_id
     *
     * @mbggenerated
     */
    public Integer getStore_id() {
        return store_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_limit.store_id
     *
     * @param store_id the value for goods_limit.store_id
     *
     * @mbggenerated
     */
    public void setStore_id(Integer store_id) {
        this.store_id = store_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_limit.merchant_proxy_id
     *
     * @return the value of goods_limit.merchant_proxy_id
     *
     * @mbggenerated
     */
    public Integer getMerchant_proxy_id() {
        return merchant_proxy_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_limit.merchant_proxy_id
     *
     * @param merchant_proxy_id the value for goods_limit.merchant_proxy_id
     *
     * @mbggenerated
     */
    public void setMerchant_proxy_id(Integer merchant_proxy_id) {
        this.merchant_proxy_id = merchant_proxy_id;
    }

	@Override
	public String toString() {
		return "GoodsLimit [id=" + id + ", gmt_create=" + gmt_create
				+ ", gmt_modified=" + gmt_modified + ", start_time="
				+ start_time + ", end_time=" + end_time + ", market_price="
				+ market_price + ", shop_price=" + shop_price + ", goods_name="
				+ goods_name + ", goods_des=" + goods_des + ", goods_img="
				+ goods_img + ", goods_storage=" + goods_storage
				+ ", is_on_sale=" + is_on_sale + ", store_id=" + store_id
				+ ", merchant_proxy_id=" + merchant_proxy_id + ", limit_count="
				+ limit_count + ", is_promote=" + is_promote + ", goodsMoney="
				+ goodsMoney + ", marketMoney=" + marketMoney + ", time="
				+ time + "]";
	}

   
  
}