package com.quxin.freshfun.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.NON_NULL)
public class GoodsDeliveryTypePOJO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_delivery_type.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_delivery_type.gmt_create
     *
     * @mbggenerated
     */
    private Long gmt_create;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_delivery_type.gmt_modified
     *
     * @mbggenerated
     */
    private Long gmt_modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_delivery_type.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_delivery_type.frequency
     *
     * @mbggenerated
     */
    private Integer frequency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_delivery_type.reserved_field
     *
     * @mbggenerated
     */
    private Byte deliveryCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_delivery_type.id
     *
     * @return the value of goods_delivery_type.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_delivery_type.id
     *
     * @param id the value for goods_delivery_type.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_delivery_type.gmt_create
     *
     * @return the value of goods_delivery_type.gmt_create
     *
     * @mbggenerated
     */
    public Long getGmt_create() {
        return gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_delivery_type.gmt_create
     *
     * @param gmt_create the value for goods_delivery_type.gmt_create
     *
     * @mbggenerated
     */
    public void setGmt_create(Long gmt_create) {
        this.gmt_create = gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_delivery_type.gmt_modified
     *
     * @return the value of goods_delivery_type.gmt_modified
     *
     * @mbggenerated
     */
    public Long getGmt_modified() {
        return gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_delivery_type.gmt_modified
     *
     * @param gmt_modified the value for goods_delivery_type.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmt_modified(Long gmt_modified) {
        this.gmt_modified = gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_delivery_type.type
     *
     * @return the value of goods_delivery_type.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_delivery_type.type
     *
     * @param type the value for goods_delivery_type.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_delivery_type.frequency
     *
     * @return the value of goods_delivery_type.frequency
     *
     * @mbggenerated
     */
    public Integer getFrequency() {
        return frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_delivery_type.frequency
     *
     * @param frequency the value for goods_delivery_type.frequency
     *
     * @mbggenerated
     */
    public void setFrequency(Integer frequency) {
        this.frequency = frequency;
    }

	public Byte getDeliveryCount() {
		return deliveryCount;
	}

	public void setDeliveryCount(Byte deliveryCount) {
		this.deliveryCount = deliveryCount;
	}
}