package com.quxin.freshfun.model;

public class OrdersPOJO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbggenerated
     */
    private Integer id;
    
    private Long order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.gmt_create
     *
     * @mbggenerated
     */
    private Long gmt_create;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.gmt_modified
     *
     * @mbggenerated
     */
    private Long gmt_modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.user_id
     *
     * @mbggenerated
     */
    private Long user_id;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.payment_method
     *
     * @mbggenerated
     */
    private Integer payment_method;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_status
     *
     * @mbggenerated
     */
    private Integer order_status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.pay_status
     *
     * @mbggenerated
     */
    private Integer pay_status;

    private Integer order_count;
    private String user_red_id;
    
    private Integer is_deleted;
    
    private Integer is_limit;

    public Integer getIs_limit() {
		return is_limit;
	}

	public void setIs_limit(Integer is_limit) {
		this.is_limit = is_limit;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.actual_price
     *
     * @mbggenerated
     */
    private Integer actual_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.reserved_field
     *
     * @mbggenerated
     */
    private String reserved_field;
    
    private String code;
    
    //
    private OrderInfo orderInfo;
    
	public Integer getIs_deleted() {
		return is_deleted;
	}

	public void setIs_deleted(Integer is_deleted) {
		this.is_deleted = is_deleted;
	}

	public OrderInfo getOrderInfo() {
		return orderInfo;
	}

	public void setOrderInfo(OrderInfo orderInfo) {
		this.orderInfo = orderInfo;
	}
    
    public Integer getOrder_count() {
		return order_count;
	}

	public void setOrder_count(Integer order_count) {
		this.order_count = order_count;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    public Long getOrder_id() {
		return order_id;
	}

	public void setOrder_id(Long order_id) {
		this.order_id = order_id;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.gmt_create
     *
     * @return the value of orders.gmt_create
     *
     * @mbggenerated
     */
    public Long getGmt_create() {
        return gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.gmt_create
     *
     * @param gmt_create the value for orders.gmt_create
     *
     * @mbggenerated
     */
    public void setGmt_create(Long gmt_create) {
        this.gmt_create = gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.gmt_modified
     *
     * @return the value of orders.gmt_modified
     *
     * @mbggenerated
     */
    public Long getGmt_modified() {
        return gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.gmt_modified
     *
     * @param gmt_modified the value for orders.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmt_modified(Long gmt_modified) {
        this.gmt_modified = gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.user_id
     *
     * @return the value of orders.user_id
     *
     * @mbggenerated
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.user_id
     *
     * @param user_id the value for orders.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.payment_method
     *
     * @return the value of orders.payment_method
     *
     * @mbggenerated
     */
    public Integer getPayment_method() {
        return payment_method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.payment_method
     *
     * @param payment_method the value for orders.payment_method
     *
     * @mbggenerated
     */
    public void setPayment_method(Integer payment_method) {
        this.payment_method = payment_method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_status
     *
     * @return the value of orders.order_status
     *
     * @mbggenerated
     */
    public Integer getOrder_status() {
        return order_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_status
     *
     * @param order_status the value for orders.order_status
     *
     * @mbggenerated
     */
    public void setOrder_status(Integer order_status) {
        this.order_status = order_status;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.pay_status
     *
     * @return the value of orders.pay_status
     *
     * @mbggenerated
     */
    public Integer getPay_status() {
        return pay_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.pay_status
     *
     * @param pay_status the value for orders.pay_status
     *
     * @mbggenerated
     */
    public void setPay_status(Integer pay_status) {
        this.pay_status = pay_status;
    }

    public String getUser_red_id() {
		return user_red_id;
	}

	public void setUser_red_id(String user_red_id) {
		this.user_red_id = user_red_id;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.actual_price
     *
     * @return the value of orders.actual_price
     *
     * @mbggenerated
     */
    public Integer getActual_price() {
        return actual_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.actual_price
     *
     * @param actual_price the value for orders.actual_price
     *
     * @mbggenerated
     */
    public void setActual_price(Integer actual_price) {
        this.actual_price = actual_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.reserved_field
     *
     * @return the value of orders.reserved_field
     *
     * @mbggenerated
     */
    public String getReserved_field() {
        return reserved_field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.reserved_field
     *
     * @param reserved_field the value for orders.reserved_field
     *
     * @mbggenerated
     */
    public void setReserved_field(String reserved_field) {
        this.reserved_field = reserved_field == null ? null : reserved_field.trim();
    }

	@Override
	public String toString() {
		return "OrdersPOJO [id=" + id + ", gmt_create=" + gmt_create
				+ ", gmt_modified=" + gmt_modified + ", user_id=" + user_id
				+", payment_method="+ payment_method + ", order_status=" + order_status
				+", pay_status="+ pay_status +", origin_price="+user_red_id
				+ ", actual_price=" + actual_price + ", reserved_field="
				+ reserved_field + ", code=" + code + ", orderInfo="
				+ orderInfo + "]";
	}
}