package com.quxin.freshfun.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.NON_NULL)
public class ShoppingCartPOJO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.sc_id
     *
     * @mbggenerated
     */
    private Integer scId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.goods_id
     *
     * @mbggenerated
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.goods_totals
     *
     * @mbggenerated
     */
    private Integer goodsTotals;
    
    private String goodsName;
    
    private Integer payStatus;
    
    private Integer isDelete;
    
    private Long createDate;
    
    private Long updateDate;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.goods_totals_price
     *
     * @mbggenerated
     */
    private Integer goodsTotalsPrice;
    
    private String goodsTotalMoney;
    
    public Long getCreateDate() {
		return createDate;
	}

	public void setCreateDate(Long createDate) {
		this.createDate = createDate;
	}

	public Long getUpdateDate() {
		return updateDate;
	}
	
	public Integer getPayStatus() {
		return payStatus;
	}

	public void setPayStatus(Integer payStatus) {
		this.payStatus = payStatus;
	}

	public Integer getIsDelete() {
		return isDelete;
	}

	public void setIsDelete(Integer isDelete) {
		this.isDelete = isDelete;
	}

	public void setUpdateDate(Long updateDate) {
		this.updateDate = updateDate;
	}
	
	public String getGoodsName() {
		return goodsName;
	}

	public void setGoodsName(String goodsName) {
		this.goodsName = goodsName;
	}

	public String getGoodsTotalMoney() {
		return goodsTotalMoney;
	}

	public void setGoodsTotalMoney(String goodsTotalMoney) {
		this.goodsTotalMoney = goodsTotalMoney;
	}

	private GoodsPOJO goods;

    public GoodsPOJO getGoods() {
		return goods;
	}

	public void setGoods(GoodsPOJO goods) {
		this.goods = goods;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.reserved_field
     *
     * @mbggenerated
     */
    private String reservedField;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.sc_id
     *
     * @return the value of shopping_cart.sc_id
     *
     * @mbggenerated
     */
    public Integer getScId() {
        return scId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.sc_id
     *
     * @param scId the value for shopping_cart.sc_id
     *
     * @mbggenerated
     */
    public void setScId(Integer scId) {
        this.scId = scId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.user_id
     *
     * @return the value of shopping_cart.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.user_id
     *
     * @param userId the value for shopping_cart.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.goods_id
     *
     * @return the value of shopping_cart.goods_id
     *
     * @mbggenerated
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.goods_id
     *
     * @param goodsId the value for shopping_cart.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.goods_totals
     *
     * @return the value of shopping_cart.goods_totals
     *
     * @mbggenerated
     */
    public Integer getGoodsTotals() {
        return goodsTotals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.goods_totals
     *
     * @param goodsTotals the value for shopping_cart.goods_totals
     *
     * @mbggenerated
     */
    public void setGoodsTotals(Integer goodsTotals) {
        this.goodsTotals = goodsTotals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.goods_totals_price
     *
     * @return the value of shopping_cart.goods_totals_price
     *
     * @mbggenerated
     */
    public Integer getGoodsTotalsPrice() {
        return goodsTotalsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.goods_totals_price
     *
     * @param goodsTotalsPrice the value for shopping_cart.goods_totals_price
     *
     * @mbggenerated
     */
    public void setGoodsTotalsPrice(Integer goodsTotalsPrice) {
        this.goodsTotalsPrice = goodsTotalsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.reserved_field
     *
     * @return the value of shopping_cart.reserved_field
     *
     * @mbggenerated
     */
    public String getReservedField() {
        return reservedField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.reserved_field
     *
     * @param reservedField the value for shopping_cart.reserved_field
     *
     * @mbggenerated
     */
    public void setReservedField(String reservedField) {
        this.reservedField = reservedField == null ? null : reservedField.trim();
    }

	@Override
	public String toString() {
		return "ShoppingCartPOJO [scId=" + scId + ", userId=" + userId
				+ ", goodsId=" + goodsId + ", goodsTotals=" + goodsTotals
				+ ", goodsName=" + goodsName + ", payStatus=" + payStatus
				+ ", isDelete=" + isDelete + ", createDate=" + createDate
				+ ", updateDate=" + updateDate + ", goodsTotalsPrice="
				+ goodsTotalsPrice + ", goodsTotalMoney=" + goodsTotalMoney
				+ ", goods=" + goods + ", reservedField=" + reservedField + "]";
	}
    
    
}