package com.quxin.freshfun.model;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.NON_NULL)
public class SpecialTheme {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_theme.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_theme.theme_des
     *
     * @mbggenerated
     */
    private String theme_des;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_theme.theme_img
     *
     * @mbggenerated
     */
    private String theme_img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_theme.theme_info_img
     *
     * @mbggenerated
     */
    private String theme_info_img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_theme.theme_content
     *
     * @mbggenerated
     */
    private String theme_content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_theme.theme_info_content
     *
     * @mbggenerated
     */
    private String theme_info_content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_theme.gmt_create
     *
     * @mbggenerated
     */
    private Integer gmt_create;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_theme.gmt_modified
     *
     * @mbggenerated
     */
    private Integer gmt_modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_theme.is_deleted
     *
     * @mbggenerated
     */
    private Byte is_deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_theme.reserved_field
     *
     * @mbggenerated
     */
    private String reserved_field;
    
    private String share_url;
    
    public String getShare_url() {
		return share_url;
	}

	public void setShare_url(String share_url) {
		this.share_url = share_url;
	}

	private List<StidVsGid> stidVsGid;

    public List<StidVsGid> getStidVsGid() {
		return stidVsGid;
	}

	public void setStidVsGid(List<StidVsGid> stidVsGid) {
		this.stidVsGid = stidVsGid;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_theme.id
     *
     * @return the value of special_theme.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_theme.id
     *
     * @param id the value for special_theme.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_theme.theme_des
     *
     * @return the value of special_theme.theme_des
     *
     * @mbggenerated
     */
    public String getTheme_des() {
        return theme_des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_theme.theme_des
     *
     * @param theme_des the value for special_theme.theme_des
     *
     * @mbggenerated
     */
    public void setTheme_des(String theme_des) {
        this.theme_des = theme_des == null ? null : theme_des.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_theme.theme_img
     *
     * @return the value of special_theme.theme_img
     *
     * @mbggenerated
     */
    public String getTheme_img() {
        return theme_img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_theme.theme_img
     *
     * @param theme_img the value for special_theme.theme_img
     *
     * @mbggenerated
     */
    public void setTheme_img(String theme_img) {
        this.theme_img = theme_img == null ? null : theme_img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_theme.theme_info_img
     *
     * @return the value of special_theme.theme_info_img
     *
     * @mbggenerated
     */
    public String getTheme_info_img() {
        return theme_info_img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_theme.theme_info_img
     *
     * @param theme_info_img the value for special_theme.theme_info_img
     *
     * @mbggenerated
     */
    public void setTheme_info_img(String theme_info_img) {
        this.theme_info_img = theme_info_img == null ? null : theme_info_img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_theme.theme_content
     *
     * @return the value of special_theme.theme_content
     *
     * @mbggenerated
     */
    public String getTheme_content() {
        return theme_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_theme.theme_content
     *
     * @param theme_content the value for special_theme.theme_content
     *
     * @mbggenerated
     */
    public void setTheme_content(String theme_content) {
        this.theme_content = theme_content == null ? null : theme_content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_theme.theme_info_content
     *
     * @return the value of special_theme.theme_info_content
     *
     * @mbggenerated
     */
    public String getTheme_info_content() {
        return theme_info_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_theme.theme_info_content
     *
     * @param theme_info_content the value for special_theme.theme_info_content
     *
     * @mbggenerated
     */
    public void setTheme_info_content(String theme_info_content) {
        this.theme_info_content = theme_info_content == null ? null : theme_info_content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_theme.gmt_create
     *
     * @return the value of special_theme.gmt_create
     *
     * @mbggenerated
     */
    public Integer getGmt_create() {
        return gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_theme.gmt_create
     *
     * @param gmt_create the value for special_theme.gmt_create
     *
     * @mbggenerated
     */
    public void setGmt_create(Integer gmt_create) {
        this.gmt_create = gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_theme.gmt_modified
     *
     * @return the value of special_theme.gmt_modified
     *
     * @mbggenerated
     */
    public Integer getGmt_modified() {
        return gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_theme.gmt_modified
     *
     * @param gmt_modified the value for special_theme.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmt_modified(Integer gmt_modified) {
        this.gmt_modified = gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_theme.is_deleted
     *
     * @return the value of special_theme.is_deleted
     *
     * @mbggenerated
     */
    public Byte getIs_deleted() {
        return is_deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_theme.is_deleted
     *
     * @param is_deleted the value for special_theme.is_deleted
     *
     * @mbggenerated
     */
    public void setIs_deleted(Byte is_deleted) {
        this.is_deleted = is_deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_theme.reserved_field
     *
     * @return the value of special_theme.reserved_field
     *
     * @mbggenerated
     */
    public String getReserved_field() {
        return reserved_field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_theme.reserved_field
     *
     * @param reserved_field the value for special_theme.reserved_field
     *
     * @mbggenerated
     */
    public void setReserved_field(String reserved_field) {
        this.reserved_field = reserved_field == null ? null : reserved_field.trim();
    }
}