package com.quxin.freshfun.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.NON_NULL)
public class SpecialMall {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_mall.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_mall.gmt_create
     *
     * @mbggenerated
     */
    private Integer gmt_create;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_mall.gmt_modified
     *
     * @mbggenerated
     */
    private Integer gmt_modified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_mall.mall_img
     *
     * @mbggenerated
     */
    private String mall_img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_mall.mall_info_img
     *
     * @mbggenerated
     */
    private String mall_info_img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_mall.mall_content
     *
     * @mbggenerated
     */
    private String mall_content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_mall.mall_info_content
     *
     * @mbggenerated
     */
    private String mall_info_content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_mall.mall_des
     *
     * @mbggenerated
     */
    private String mall_des;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_mall.is_deleted
     *
     * @mbggenerated
     */
    private Byte is_deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_mall.reserved_field
     *
     * @mbggenerated
     */
    private String reserved_field;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_mall.id
     *
     * @return the value of special_mall.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_mall.id
     *
     * @param id the value for special_mall.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_mall.gmt_create
     *
     * @return the value of special_mall.gmt_create
     *
     * @mbggenerated
     */
    public Integer getGmt_create() {
        return gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_mall.gmt_create
     *
     * @param gmt_create the value for special_mall.gmt_create
     *
     * @mbggenerated
     */
    public void setGmt_create(Integer gmt_create) {
        this.gmt_create = gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_mall.gmt_modified
     *
     * @return the value of special_mall.gmt_modified
     *
     * @mbggenerated
     */
    public Integer getGmt_modified() {
        return gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_mall.gmt_modified
     *
     * @param gmt_modified the value for special_mall.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmt_modified(Integer gmt_modified) {
        this.gmt_modified = gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_mall.mall_img
     *
     * @return the value of special_mall.mall_img
     *
     * @mbggenerated
     */
    public String getMall_img() {
        return mall_img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_mall.mall_img
     *
     * @param mall_img the value for special_mall.mall_img
     *
     * @mbggenerated
     */
    public void setMall_img(String mall_img) {
        this.mall_img = mall_img == null ? null : mall_img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_mall.mall_info_img
     *
     * @return the value of special_mall.mall_info_img
     *
     * @mbggenerated
     */
    public String getMall_info_img() {
        return mall_info_img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_mall.mall_info_img
     *
     * @param mall_info_img the value for special_mall.mall_info_img
     *
     * @mbggenerated
     */
    public void setMall_info_img(String mall_info_img) {
        this.mall_info_img = mall_info_img == null ? null : mall_info_img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_mall.mall_content
     *
     * @return the value of special_mall.mall_content
     *
     * @mbggenerated
     */
    public String getMall_content() {
        return mall_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_mall.mall_content
     *
     * @param mall_content the value for special_mall.mall_content
     *
     * @mbggenerated
     */
    public void setMall_content(String mall_content) {
        this.mall_content = mall_content == null ? null : mall_content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_mall.mall_info_content
     *
     * @return the value of special_mall.mall_info_content
     *
     * @mbggenerated
     */
    public String getMall_info_content() {
        return mall_info_content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_mall.mall_info_content
     *
     * @param mall_info_content the value for special_mall.mall_info_content
     *
     * @mbggenerated
     */
    public void setMall_info_content(String mall_info_content) {
        this.mall_info_content = mall_info_content == null ? null : mall_info_content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_mall.mall_des
     *
     * @return the value of special_mall.mall_des
     *
     * @mbggenerated
     */
    public String getMall_des() {
        return mall_des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_mall.mall_des
     *
     * @param mall_des the value for special_mall.mall_des
     *
     * @mbggenerated
     */
    public void setMall_des(String mall_des) {
        this.mall_des = mall_des == null ? null : mall_des.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_mall.is_deleted
     *
     * @return the value of special_mall.is_deleted
     *
     * @mbggenerated
     */
    public Byte getIs_deleted() {
        return is_deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_mall.is_deleted
     *
     * @param is_deleted the value for special_mall.is_deleted
     *
     * @mbggenerated
     */
    public void setIs_deleted(Byte is_deleted) {
        this.is_deleted = is_deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column special_mall.reserved_field
     *
     * @return the value of special_mall.reserved_field
     *
     * @mbggenerated
     */
    public String getReserved_field() {
        return reserved_field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column special_mall.reserved_field
     *
     * @param reserved_field the value for special_mall.reserved_field
     *
     * @mbggenerated
     */
    public void setReserved_field(String reserved_field) {
        this.reserved_field = reserved_field == null ? null : reserved_field.trim();
    }
}