package com.quxin.freshfun.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.NON_NULL)
public class SpecialMall {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_mall.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_mall.gmt_create
     *
     * @mbggenerated
     */
    private Integer gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_mall.gmt_modified
     *
     * @mbggenerated
     */
    private Integer gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_mall.mall_img
     *
     * @mbggenerated
     */
    private String mallImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_mall.mall_info_img
     *
     * @mbggenerated
     */
    private String mallInfoImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_mall.mall_content
     *
     * @mbggenerated
     */
    private String mallContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_mall.mall_info_content
     *
     * @mbggenerated
     */
    private String mallInfoContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_mall.mall_des
     *
     * @mbggenerated
     */
    private String mallDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_mall.is_deleted
     *
     * @mbggenerated
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_mall.reserved_field
     *
     * @mbggenerated
     */
    private String reservedField;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getGmtCreate() {
        return gmtCreate;
    }

    public void setGmtCreate(Integer gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    public Integer getGmtModified() {
        return gmtModified;
    }

    public void setGmtModified(Integer gmtModified) {
        this.gmtModified = gmtModified;
    }

    public String getMallImg() {
        return mallImg;
    }

    public void setMallImg(String mallImg) {
        this.mallImg = mallImg;
    }

    public String getMallInfoImg() {
        return mallInfoImg;
    }

    public void setMallInfoImg(String mallInfoImg) {
        this.mallInfoImg = mallInfoImg;
    }

    public String getMallContent() {
        return mallContent;
    }

    public void setMallContent(String mallContent) {
        this.mallContent = mallContent;
    }

    public String getMallInfoContent() {
        return mallInfoContent;
    }

    public void setMallInfoContent(String mallInfoContent) {
        this.mallInfoContent = mallInfoContent;
    }

    public String getMallDes() {
        return mallDes;
    }

    public void setMallDes(String mallDes) {
        this.mallDes = mallDes;
    }

    public Byte getIsDeleted() {
        return isDeleted;
    }

    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    public String getReservedField() {
        return reservedField;
    }

    public void setReservedField(String reservedField) {
        this.reservedField = reservedField;
    }
}