package com.quxin.freshfun.model;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.NON_NULL)
public class SpecialTheme {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_theme.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_theme.theme_des
     *
     * @mbggenerated
     */
    private String themeDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_theme.theme_img
     *
     * @mbggenerated
     */
    private String themeImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_theme.theme_info_img
     *
     * @mbggenerated
     */
    private String themeInfoImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_theme.theme_content
     *
     * @mbggenerated
     */
    private String themeContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_theme.theme_info_content
     *
     * @mbggenerated
     */
    private String themeInfoContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_theme.gmt_create
     *
     * @mbggenerated
     */
    private Integer gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_theme.gmt_modified
     *
     * @mbggenerated
     */
    private Integer gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_theme.is_deleted
     *
     * @mbggenerated
     */
    private Byte isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column special_theme.reserved_field
     *
     * @mbggenerated
     */
    private String reservedField;
    
    private String shareUrl;

	private List<StidVsGid> stidVsGid;

    public List<StidVsGid> getStidVsGid() {
		return stidVsGid;
	}

	public void setStidVsGid(List<StidVsGid> stidVsGid) {
		this.stidVsGid = stidVsGid;
	}

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getThemeDes() {
        return themeDes;
    }

    public void setThemeDes(String themeDes) {
        this.themeDes = themeDes;
    }

    public String getThemeImg() {
        return themeImg;
    }

    public void setThemeImg(String themeImg) {
        this.themeImg = themeImg;
    }

    public String getThemeInfoImg() {
        return themeInfoImg;
    }

    public void setThemeInfoImg(String themeInfoImg) {
        this.themeInfoImg = themeInfoImg;
    }

    public String getThemeContent() {
        return themeContent;
    }

    public void setThemeContent(String themeContent) {
        this.themeContent = themeContent;
    }

    public String getThemeInfoContent() {
        return themeInfoContent;
    }

    public void setThemeInfoContent(String themeInfoContent) {
        this.themeInfoContent = themeInfoContent;
    }

    public Integer getGmtCreate() {
        return gmtCreate;
    }

    public void setGmtCreate(Integer gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    public Integer getGmtModified() {
        return gmtModified;
    }

    public void setGmtModified(Integer gmtModified) {
        this.gmtModified = gmtModified;
    }

    public Byte getIsDeleted() {
        return isDeleted;
    }

    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    public String getReservedField() {
        return reservedField;
    }

    public void setReservedField(String reservedField) {
        this.reservedField = reservedField;
    }

    public String getShareUrl() {
        return shareUrl;
    }

    public void setShareUrl(String shareUrl) {
        this.shareUrl = shareUrl;
    }
}