package com.quxin.freshfun.model;

import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class StidVsGid {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stid_vs_gid.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stid_vs_gid.theme_id
     *
     * @mbggenerated
     */
    private Integer themeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stid_vs_gid.goods_id
     *
     * @mbggenerated
     */
    private Integer goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stid_vs_gid.reserved_field
     *
     * @mbggenerated
     */
    private String reservedField;
    
    private GoodsPOJO goods;

	public GoodsPOJO getGoods() {
		return goods;
	}

	public void setGoods(GoodsPOJO goods) {
		this.goods = goods;
	}

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getThemeId() {
        return themeId;
    }

    public void setThemeId(Integer themeId) {
        this.themeId = themeId;
    }

    public Integer getGoodsId() {
        return goodsId;
    }

    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    public String getReservedField() {
        return reservedField;
    }

    public void setReservedField(String reservedField) {
        this.reservedField = reservedField;
    }
}