package com.quxin.freshfun.model;

public class UserRevenueDetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_revenue_details.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_revenue_details.user_revenue_id
     *
     * @mbggenerated
     */
    private Integer user_revenue_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_revenue_details.order_info_id
     *
     * @mbggenerated
     */
    private String order_info_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_revenue_details.revenue_detail_price
     *
     * @mbggenerated
     */
    private Integer revenue_detail_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_revenue_details.create_date
     *
     * @mbggenerated
     */
    private Long create_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_revenue_details.update_date
     *
     * @mbggenerated
     */
    private Long update_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_revenue_details.revenue_type
     *
     * @mbggenerated
     */
    private Integer revenue_type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_revenue_details.is_delete
     *
     * @mbggenerated
     */
    private Integer is_delete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_revenue_details.reset
     *
     * @mbggenerated
     */
    private String reset;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_revenue_details.id
     *
     * @return the value of user_revenue_details.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_revenue_details.id
     *
     * @param id the value for user_revenue_details.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_revenue_details.user_revenue_id
     *
     * @return the value of user_revenue_details.user_revenue_id
     *
     * @mbggenerated
     */
    public Integer getUser_revenue_id() {
        return user_revenue_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_revenue_details.user_revenue_id
     *
     * @param user_revenue_id the value for user_revenue_details.user_revenue_id
     *
     * @mbggenerated
     */
    public void setUser_revenue_id(Integer user_revenue_id) {
        this.user_revenue_id = user_revenue_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_revenue_details.order_info_id
     *
     * @return the value of user_revenue_details.order_info_id
     *
     * @mbggenerated
     */
    public String getOrder_info_id() {
        return order_info_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_revenue_details.order_info_id
     *
     * @param order_info_id the value for user_revenue_details.order_info_id
     *
     * @mbggenerated
     */
    public void setOrder_info_id(String order_info_id) {
        this.order_info_id = order_info_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_revenue_details.revenue_detail_price
     *
     * @return the value of user_revenue_details.revenue_detail_price
     *
     * @mbggenerated
     */
    public Integer getRevenue_detail_price() {
        return revenue_detail_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_revenue_details.revenue_detail_price
     *
     * @param revenue_detail_price the value for user_revenue_details.revenue_detail_price
     *
     * @mbggenerated
     */
    public void setRevenue_detail_price(Integer revenue_detail_price) {
        this.revenue_detail_price = revenue_detail_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_revenue_details.create_date
     *
     * @return the value of user_revenue_details.create_date
     *
     * @mbggenerated
     */
    public Long getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_revenue_details.create_date
     *
     * @param create_date the value for user_revenue_details.create_date
     *
     * @mbggenerated
     */
    public void setCreate_date(Long create_date) {
        this.create_date = create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_revenue_details.update_date
     *
     * @return the value of user_revenue_details.update_date
     *
     * @mbggenerated
     */
    public Long getUpdate_date() {
        return update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_revenue_details.update_date
     *
     * @param update_date the value for user_revenue_details.update_date
     *
     * @mbggenerated
     */
    public void setUpdate_date(Long update_date) {
        this.update_date = update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_revenue_details.revenue_type
     *
     * @return the value of user_revenue_details.revenue_type
     *
     * @mbggenerated
     */
    public Integer getRevenue_type() {
        return revenue_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_revenue_details.revenue_type
     *
     * @param revenue_type the value for user_revenue_details.revenue_type
     *
     * @mbggenerated
     */
    public void setRevenue_type(Integer revenue_type) {
        this.revenue_type = revenue_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_revenue_details.is_delete
     *
     * @return the value of user_revenue_details.is_delete
     *
     * @mbggenerated
     */
    public Integer getIs_delete() {
        return is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_revenue_details.is_delete
     *
     * @param is_delete the value for user_revenue_details.is_delete
     *
     * @mbggenerated
     */
    public void setIs_delete(Integer is_delete) {
        this.is_delete = is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_revenue_details.reset
     *
     * @return the value of user_revenue_details.reset
     *
     * @mbggenerated
     */
    public String getReset() {
        return reset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_revenue_details.reset
     *
     * @param reset the value for user_revenue_details.reset
     *
     * @mbggenerated
     */
    public void setReset(String reset) {
        this.reset = reset == null ? null : reset.trim();
    }

	public UserRevenueDetails(Integer user_revenue_id, String order_info_id,
			Integer revenue_detail_price, Long create_date, Long update_date,
			Integer revenue_type) {
		super();
		this.user_revenue_id = user_revenue_id;
		this.order_info_id = order_info_id;
		this.revenue_detail_price = revenue_detail_price;
		this.create_date = create_date;
		this.update_date = update_date;
		this.revenue_type = revenue_type;
	}

	public UserRevenueDetails() {
		super();
	}
}