package com.quxin.freshfun.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.NON_NULL)
public class UserRevenue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_revenue.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_revenue.user_id
     *
     * @mbggenerated
     */
    private Long user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_revenue.order_id
     *
     * @mbggenerated
     */
    private String order_id;
    
    private String revenue_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_revenue.price
     *
     * @mbggenerated
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_revenue.in_state
     *
     * @mbggenerated
     */
    private Integer in_state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_revenue.create_date
     *
     * @mbggenerated
     */
    private Long create_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_revenue.update_date
     *
     * @mbggenerated
     */
    private Long update_date;
    
    private Integer delivery_type;
    
    private String money;
    
    public String getMoney() {
		return money;
	}

	public void setMoney(String money) {
		this.money = money;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_revenue.is_delete
     *
     * @mbggenerated
     */
    private Integer is_delete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_revenue.id
     *
     * @return the value of user_revenue.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_revenue.id
     *
     * @param id the value for user_revenue.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getDelivery_type() {
		return delivery_type;
	}

	public void setDelivery_type(Integer delivery_type) {
		this.delivery_type = delivery_type;
	}
	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_revenue.user_id
     *
     * @return the value of user_revenue.user_id
     *
     * @mbggenerated
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_revenue.user_id
     *
     * @param user_id the value for user_revenue.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_revenue.order_id
     *
     * @return the value of user_revenue.order_id
     *
     * @mbggenerated
     */
    public String getOrder_id() {
        return order_id;
    }


	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_revenue.order_id
     *
     * @param order_id the value for user_revenue.order_id
     *
     * @mbggenerated
     */
    public void setOrder_id(String order_id) {
        this.order_id = order_id;
    }
    
    public String getRevenue_name() {
		return revenue_name;
	}

	public void setRevenue_name(String revenue_name) {
		this.revenue_name = revenue_name;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_revenue.price
     *
     * @return the value of user_revenue.price
     *
     * @mbggenerated
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_revenue.price
     *
     * @param price the value for user_revenue.price
     *
     * @mbggenerated
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_revenue.in_state
     *
     * @return the value of user_revenue.in_state
     *
     * @mbggenerated
     */
    public Integer getIn_state() {
        return in_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_revenue.in_state
     *
     * @param in_state the value for user_revenue.in_state
     *
     * @mbggenerated
     */
    public void setIn_state(Integer in_state) {
        this.in_state = in_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_revenue.create_date
     *
     * @return the value of user_revenue.create_date
     *
     * @mbggenerated
     */
    public Long getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_revenue.create_date
     *
     * @param create_date the value for user_revenue.create_date
     *
     * @mbggenerated
     */
    public void setCreate_date(Long create_date) {
        this.create_date = create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_revenue.update_date
     *
     * @return the value of user_revenue.update_date
     *
     * @mbggenerated
     */
    public Long getUpdate_date() {
        return update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_revenue.update_date
     *
     * @param update_date the value for user_revenue.update_date
     *
     * @mbggenerated
     */
    public void setUpdate_date(Long update_date) {
        this.update_date = update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_revenue.is_delete
     *
     * @return the value of user_revenue.is_delete
     *
     * @mbggenerated
     */
    public Integer getIs_delete() {
        return is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_revenue.is_delete
     *
     * @param is_delete the value for user_revenue.is_delete
     *
     * @mbggenerated
     */
    public void setIs_delete(Integer is_delete) {
        this.is_delete = is_delete;
    }

    //����
	public UserRevenue() {
		super();
	}

	public UserRevenue(Long user_id, String order_id, Integer price,
			Long create_date, Long update_date,Byte notDeliveryCount) {
		super();
		this.user_id = user_id;
		this.order_id = order_id;
		this.price = price;
		this.create_date = create_date;
		this.update_date = update_date;
	}

	public UserRevenue(Long user_id, String order_id, Integer price, Long create_date, Long update_date) {
		super();
		this.user_id = user_id;
		this.order_id = order_id;
		this.price = price;
		this.create_date = create_date;
		this.update_date = update_date;
	}
}