package com.quxin.freshfun.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.NON_NULL)
public class UsersPOJO {
    private Integer id;

    private Long gmt_create;

    private Long gmt_modified;

    private String user_name;

    private String user_head_url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.mobile_phone
     *
     * @mbggenerated
     */
    private String mobile_phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.device_id
     *
     * @mbggenerated
     */
    private String device_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.wx_id
     *
     * @mbggenerated
     */
    private String wx_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.wz_id
     *
     * @mbggenerated
     */
    private String wz_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.login_method
     *
     * @mbggenerated
     */
    private String login_method;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.is_received
     *
     * @mbggenerated
     */
    private Byte is_received;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.parent_id
     *
     * @mbggenerated
     */
    private Long parent_id;
    

    public Long getParent_id() {
		return parent_id;
	}

	public void setParent_id(Long parent_id) {
		this.parent_id = parent_id;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.reg_time
     *
     * @mbggenerated
     */
    private Long reg_time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_credit
     *
     * @mbggenerated
     */
    private Byte user_credit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_money
     *
     * @mbggenerated
     */
    private Integer user_money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.frozen_money
     *
     * @mbggenerated
     */
    private Integer frozen_money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_identify
     *
     * @mbggenerated
     */
    private Byte user_identify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.income_identify
     *
     * @mbggenerated
     */
    private Byte income_identify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_enter
     *
     * @mbggenerated
     */
    private Byte user_enter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_info_id
     *
     * @mbggenerated
     */
    private Integer user_info_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.is_deleted
     *
     * @mbggenerated
     */
    private Byte is_deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.user_address
     *
     * @mbggenerated
     */
    private Integer user_address;

    private Long userId;

    private Long gmtCreate;

    private Long gmtModified;

    private String userName;

    private String userHeadUrl;

    private String mobilePhone;

    private String deviceId;

    private String wxId;

    private String wzId;

    private String loginMethod;

    private Byte isReceived;

    private Integer parentId;

    private Long regTime;

    private Byte userCredit;

    private Integer userMoney;

    private Integer frozenMoney;

    private Byte userIdentify;

    private Byte incomeIdentify;

    private Byte userEnter;

    private Integer userInfoId;

    private Byte isDeleted;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.gmt_create
     *
     * @return the value of users.gmt_create
     *
     * @mbggenerated
     */
    public Long getGmt_create() {
        return gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.gmt_create
     *
     * @param gmt_create the value for users.gmt_create
     *
     * @mbggenerated
     */
    public void setGmt_create(Long gmt_create) {
        this.gmt_create = gmt_create;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.gmt_modified
     *
     * @return the value of users.gmt_modified
     *
     * @mbggenerated
     */
    public Long getGmt_modified() {
        return gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.gmt_modified
     *
     * @param gmt_modified the value for users.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmt_modified(Long gmt_modified) {
        this.gmt_modified = gmt_modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_name
     *
     * @return the value of users.user_name
     *
     * @mbggenerated
     */
    public String getUser_name() {
        return user_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_name
     *
     * @param user_name the value for users.user_name
     *
     * @mbggenerated
     */
    public void setUser_name(String user_name) {
        this.user_name = user_name == null ? null : user_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_head_url
     *
     * @return the value of users.user_head_url
     *
     * @mbggenerated
     */
    public String getUser_head_url() {
        return user_head_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_head_url
     *
     * @param user_head_url the value for users.user_head_url
     *
     * @mbggenerated
     */
    public void setUser_head_url(String user_head_url) {
        this.user_head_url = user_head_url == null ? null : user_head_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.mobile_phone
     *
     * @return the value of users.mobile_phone
     *
     * @mbggenerated
     */
    public String getMobile_phone() {
        return mobile_phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.mobile_phone
     *
     * @param mobile_phone the value for users.mobile_phone
     *
     * @mbggenerated
     */
    public void setMobile_phone(String mobile_phone) {
        this.mobile_phone = mobile_phone == null ? null : mobile_phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.device_id
     *
     * @return the value of users.device_id
     *
     * @mbggenerated
     */
    public String getDevice_id() {
        return device_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.device_id
     *
     * @param device_id the value for users.device_id
     *
     * @mbggenerated
     */
    public void setDevice_id(String device_id) {
        this.device_id = device_id == null ? null : device_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.wx_id
     *
     * @return the value of users.wx_id
     *
     * @mbggenerated
     */
    public String getWx_id() {
        return wx_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.wx_id
     *
     * @param wx_id the value for users.wx_id
     *
     * @mbggenerated
     */
    public void setWx_id(String wx_id) {
        this.wx_id = wx_id == null ? null : wx_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.wz_id
     *
     * @return the value of users.wz_id
     *
     * @mbggenerated
     */
    public String getWz_id() {
        return wz_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.wz_id
     *
     * @param wz_id the value for users.wz_id
     *
     * @mbggenerated
     */
    public void setWz_id(String wz_id) {
        this.wz_id = wz_id == null ? null : wz_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.login_method
     *
     * @return the value of users.login_method
     *
     * @mbggenerated
     */
    public String getLogin_method() {
        return login_method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.login_method
     *
     * @param login_method the value for users.login_method
     *
     * @mbggenerated
     */
    public void setLogin_method(String login_method) {
        this.login_method = login_method == null ? null : login_method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.is_received
     *
     * @return the value of users.is_received
     *
     * @mbggenerated
     */
    public Byte getIs_received() {
        return is_received;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.is_received
     *
     * @param is_received the value for users.is_received
     *
     * @mbggenerated
     */
    public void setIs_received(Byte is_received) {
        this.is_received = is_received;
    }

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.reg_time
     *
     * @return the value of users.reg_time
     *
     * @mbggenerated
     */
    public Long getReg_time() {
        return reg_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.reg_time
     *
     * @param reg_time the value for users.reg_time
     *
     * @mbggenerated
     */
    public void setReg_time(Long reg_time) {
        this.reg_time = reg_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_credit
     *
     * @return the value of users.user_credit
     *
     * @mbggenerated
     */
    public Byte getUser_credit() {
        return user_credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_credit
     *
     * @param user_credit the value for users.user_credit
     *
     * @mbggenerated
     */
    public void setUser_credit(Byte user_credit) {
        this.user_credit = user_credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_money
     *
     * @return the value of users.user_money
     *
     * @mbggenerated
     */
    public Integer getUser_money() {
        return user_money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_money
     *
     * @param user_money the value for users.user_money
     *
     * @mbggenerated
     */
    public void setUser_money(Integer user_money) {
        this.user_money = user_money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.frozen_money
     *
     * @return the value of users.frozen_money
     *
     * @mbggenerated
     */
    public Integer getFrozen_money() {
        return frozen_money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.frozen_money
     *
     * @param frozen_money the value for users.frozen_money
     *
     * @mbggenerated
     */
    public void setFrozen_money(Integer frozen_money) {
        this.frozen_money = frozen_money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_identify
     *
     * @return the value of users.user_identify
     *
     * @mbggenerated
     */
    public Byte getUser_identify() {
        return user_identify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_identify
     *
     * @param user_identify the value for users.user_identify
     *
     * @mbggenerated
     */
    public void setUser_identify(Byte user_identify) {
        this.user_identify = user_identify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.income_identify
     *
     * @return the value of users.income_identify
     *
     * @mbggenerated
     */
    public Byte getIncome_identify() {
        return income_identify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.income_identify
     *
     * @param income_identify the value for users.income_identify
     *
     * @mbggenerated
     */
    public void setIncome_identify(Byte income_identify) {
        this.income_identify = income_identify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_enter
     *
     * @return the value of users.user_enter
     *
     * @mbggenerated
     */
    public Byte getUser_enter() {
        return user_enter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_enter
     *
     * @param user_enter the value for users.user_enter
     *
     * @mbggenerated
     */
    public void setUser_enter(Byte user_enter) {
        this.user_enter = user_enter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_info_id
     *
     * @return the value of users.user_info_id
     *
     * @mbggenerated
     */
    public Integer getUser_info_id() {
        return user_info_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_info_id
     *
     * @param user_info_id the value for users.user_info_id
     *
     * @mbggenerated
     */
    public void setUser_info_id(Integer user_info_id) {
        this.user_info_id = user_info_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.is_deleted
     *
     * @return the value of users.is_deleted
     *
     * @mbggenerated
     */
    public Byte getIs_deleted() {
        return is_deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.is_deleted
     *
     * @param is_deleted the value for users.is_deleted
     *
     * @mbggenerated
     */
    public void setIs_deleted(Byte is_deleted) {
        this.is_deleted = is_deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.user_address
     *
     * @return the value of users.user_address
     *
     * @mbggenerated
     */
    public Integer getuser_address() {
        return user_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_address
     *
     * @param user_address the value for users.user_address
     *
     * @mbggenerated
     */
    public void setuser_address(Integer user_address) {
        this.user_address = user_address;
    }
    public Long getUserId() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Long getGmtCreate() {
        return gmtCreate;
    }

    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    public Long getGmtModified() {
        return gmtModified;
    }

    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserHeadUrl() {
        return userHeadUrl;
    }

    public void setUserHeadUrl(String userHeadUrl) {
        this.userHeadUrl = userHeadUrl;
    }

    public String getMobilePhone() {
        return mobilePhone;
    }

    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    public String getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    public String getWxId() {
        return wxId;
    }

    public void setWxId(String wxId) {
        this.wxId = wxId;
    }

    public String getWzId() {
        return wzId;
    }

    public void setWzId(String wzId) {
        this.wzId = wzId;
    }

    public String getLoginMethod() {
        return loginMethod;
    }

    public void setLoginMethod(String loginMethod) {
        this.loginMethod = loginMethod;
    }

    public Byte getIsReceived() {
        return isReceived;
    }

    public void setIsReceived(Byte isReceived) {
        this.isReceived = isReceived;
    }

    public Integer getParentId() {
        return parentId;
    }

    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    public Long getRegTime() {
        return regTime;
    }

    public void setRegTime(Long regTime) {
        this.regTime = regTime;
    }

    public Byte getUserCredit() {
        return userCredit;
    }

    public void setUserCredit(Byte userCredit) {
        this.userCredit = userCredit;
    }

    public Integer getUserMoney() {
        return userMoney;
    }

    public void setUserMoney(Integer userMoney) {
        this.userMoney = userMoney;
    }

    public Integer getFrozenMoney() {
        return frozenMoney;
    }

    public void setFrozenMoney(Integer frozenMoney) {
        this.frozenMoney = frozenMoney;
    }

    public Byte getUserIdentify() {
        return userIdentify;
    }

    public void setUserIdentify(Byte userIdentify) {
        this.userIdentify = userIdentify;
    }

    public Byte getIncomeIdentify() {
        return incomeIdentify;
    }

    public void setIncomeIdentify(Byte incomeIdentify) {
        this.incomeIdentify = incomeIdentify;
    }

    public Byte getUserEnter() {
        return userEnter;
    }

    public void setUserEnter(Byte userEnter) {
        this.userEnter = userEnter;
    }

    public Integer getUserInfoId() {
        return userInfoId;
    }

    public void setUserInfoId(Integer userInfoId) {
        this.userInfoId = userInfoId;
    }

    public Byte getIsDeleted() {
        return isDeleted;
    }

    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }
}