package com.quxin.freshfun.model;

public class UserOutcome {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_outcome.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_outcome.user_id
     *
     * @mbggenerated
     */
    private Long user_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_outcome.order_id
     *
     * @mbggenerated
     */
    private String order_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_outcome.out_price
     *
     * @mbggenerated
     */
    private Integer out_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_outcome.create_date
     *
     * @mbggenerated
     */
    private Long create_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_outcome.update_date
     *
     * @mbggenerated
     */
    private Long update_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_outcome.is_delete
     *
     * @mbggenerated
     */
    private Integer is_delete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_outcome.reset
     *
     * @mbggenerated
     */
    private String outcome_name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_outcome.id
     *
     * @return the value of user_outcome.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_outcome.id
     *
     * @param id the value for user_outcome.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_outcome.user_id
     *
     * @return the value of user_outcome.user_id
     *
     * @mbggenerated
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_outcome.user_id
     *
     * @param user_id the value for user_outcome.user_id
     *
     * @mbggenerated
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_outcome.order_id
     *
     * @return the value of user_outcome.order_id
     *
     * @mbggenerated
     */
    public String getOrder_id() {
        return order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_outcome.order_id
     *
     * @param order_id the value for user_outcome.order_id
     *
     * @mbggenerated
     */
    public void setOrder_id(String order_id) {
        this.order_id = order_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_outcome.out_price
     *
     * @return the value of user_outcome.out_price
     *
     * @mbggenerated
     */
    public Integer getOut_price() {
        return out_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_outcome.out_price
     *
     * @param out_price the value for user_outcome.out_price
     *
     * @mbggenerated
     */
    public void setOut_price(Integer out_price) {
        this.out_price = out_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_outcome.create_date
     *
     * @return the value of user_outcome.create_date
     *
     * @mbggenerated
     */
    public Long getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_outcome.create_date
     *
     * @param create_date the value for user_outcome.create_date
     *
     * @mbggenerated
     */
    public void setCreate_date(Long create_date) {
        this.create_date = create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_outcome.update_date
     *
     * @return the value of user_outcome.update_date
     *
     * @mbggenerated
     */
    public Long getUpdate_date() {
        return update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_outcome.update_date
     *
     * @param update_date the value for user_outcome.update_date
     *
     * @mbggenerated
     */
    public void setUpdate_date(Long update_date) {
        this.update_date = update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_outcome.is_delete
     *
     * @return the value of user_outcome.is_delete
     *
     * @mbggenerated
     */
    public Integer getIs_delete() {
        return is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_outcome.is_delete
     *
     * @param is_delete the value for user_outcome.is_delete
     *
     * @mbggenerated
     */
    public void setIs_delete(Integer is_delete) {
        this.is_delete = is_delete;
    }

	public String getOutcome_name() {
		return outcome_name;
	}

	public void setOutcome_name(String outcome_name) {
		this.outcome_name = outcome_name;
	}

	public UserOutcome(Long user_id, String order_id, Integer out_price,
			Long create_date, Long update_date) {
		super();
		this.user_id = user_id;
		this.order_id = order_id;
		this.out_price = out_price;
		this.create_date = create_date;
		this.update_date = update_date;
	}

	public UserOutcome() {
		super();
	}
}