package com.quxin.freshfun.model;

public class UserOutcomeDetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_outcome_details.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_outcome_details.outcome_id
     *
     * @mbggenerated
     */
    private Integer outcome_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_outcome_details.order_info_id
     *
     * @mbggenerated
     */
    private String order_info_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_outcome_details.outcome_price
     *
     * @mbggenerated
     */
    private Integer outcome_price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_outcome_details.create_date
     *
     * @mbggenerated
     */
    private Long create_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_outcome_details.update_date
     *
     * @mbggenerated
     */
    private Long update_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_outcome_details.is_delete
     *
     * @mbggenerated
     */
    private Integer is_delete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_outcome_details.reset
     *
     * @mbggenerated
     */
    private String reset;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_outcome_details.id
     *
     * @return the value of user_outcome_details.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_outcome_details.id
     *
     * @param id the value for user_outcome_details.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_outcome_details.outcome_id
     *
     * @return the value of user_outcome_details.outcome_id
     *
     * @mbggenerated
     */
    public Integer getOutcome_id() {
        return outcome_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_outcome_details.outcome_id
     *
     * @param outcome_id the value for user_outcome_details.outcome_id
     *
     * @mbggenerated
     */
    public void setOutcome_id(Integer outcome_id) {
        this.outcome_id = outcome_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_outcome_details.order_info_id
     *
     * @return the value of user_outcome_details.order_info_id
     *
     * @mbggenerated
     */
    public String getOrder_info_id() {
        return order_info_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_outcome_details.order_info_id
     *
     * @param order_info_id the value for user_outcome_details.order_info_id
     *
     * @mbggenerated
     */
    public void setOrder_info_id(String order_info_id) {
        this.order_info_id = order_info_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_outcome_details.outcome_price
     *
     * @return the value of user_outcome_details.outcome_price
     *
     * @mbggenerated
     */
    public Integer getOutcome_price() {
        return outcome_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_outcome_details.outcome_price
     *
     * @param outcome_price the value for user_outcome_details.outcome_price
     *
     * @mbggenerated
     */
    public void setOutcome_price(Integer outcome_price) {
        this.outcome_price = outcome_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_outcome_details.create_date
     *
     * @return the value of user_outcome_details.create_date
     *
     * @mbggenerated
     */
    public Long getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_outcome_details.create_date
     *
     * @param create_date the value for user_outcome_details.create_date
     *
     * @mbggenerated
     */
    public void setCreate_date(Long create_date) {
        this.create_date = create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_outcome_details.update_date
     *
     * @return the value of user_outcome_details.update_date
     *
     * @mbggenerated
     */
    public Long getUpdate_date() {
        return update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_outcome_details.update_date
     *
     * @param update_date the value for user_outcome_details.update_date
     *
     * @mbggenerated
     */
    public void setUpdate_date(Long update_date) {
        this.update_date = update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_outcome_details.is_delete
     *
     * @return the value of user_outcome_details.is_delete
     *
     * @mbggenerated
     */
    public Integer getIs_delete() {
        return is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_outcome_details.is_delete
     *
     * @param is_delete the value for user_outcome_details.is_delete
     *
     * @mbggenerated
     */
    public void setIs_delete(Integer is_delete) {
        this.is_delete = is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_outcome_details.reset
     *
     * @return the value of user_outcome_details.reset
     *
     * @mbggenerated
     */
    public String getReset() {
        return reset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_outcome_details.reset
     *
     * @param reset the value for user_outcome_details.reset
     *
     * @mbggenerated
     */
    public void setReset(String reset) {
        this.reset = reset == null ? null : reset.trim();
    }

	public UserOutcomeDetails(Integer outcome_id, String order_info_id,
			Integer outcome_price, Long create_date, Long update_date) {
		super();
		this.outcome_id = outcome_id;
		this.order_info_id = order_info_id;
		this.outcome_price = outcome_price;
		this.create_date = create_date;
		this.update_date = update_date;
	}

	public UserOutcomeDetails() {
		super();
	}
    
}