package com.quxin.freshfun.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.NON_NULL)
public class Withdraw {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw.withdraw_price
     *
     * @mbggenerated
     */
    private Integer withdrawPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw.create_date
     *
     * @mbggenerated
     */
    private Long createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw.state
     *
     * @mbggenerated
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw.withdraw_type
     *
     * @mbggenerated
     */
    private Integer withdrawType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw.deal_persion
     *
     * @mbggenerated
     */
    private String dealPersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw.update_date
     *
     * @mbggenerated
     */
    private Long updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw.is_delete
     *
     * @mbggenerated
     */
    private Integer isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column withdraw.reset
     *
     * @mbggenerated
     */
    private String paymentAccount;
    
    private String withdrawMoney;
    
    public String getWithdrawMoney() {
		return withdrawMoney;
	}

	public void setWithdrawMoney(String withdrawMoney) {
		this.withdrawMoney = withdrawMoney;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw.id
     *
     * @return the value of withdraw.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw.id
     *
     * @param id the value for withdraw.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw.user_id
     *
     * @return the value of withdraw.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw.user_id
     *
     * @param userId the value for withdraw.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw.withdraw_price
     *
     * @return the value of withdraw.withdraw_price
     *
     * @mbggenerated
     */
    public Integer getWithdrawPrice() {
        return withdrawPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw.withdraw_price
     *
     * @param withdrawPrice the value for withdraw.withdraw_price
     *
     * @mbggenerated
     */
    public void setWithdrawPrice(Integer withdrawPrice) {
        this.withdrawPrice = withdrawPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw.create_date
     *
     * @return the value of withdraw.create_date
     *
     * @mbggenerated
     */
    public Long getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw.create_date
     *
     * @param createDate the value for withdraw.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Long createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw.state
     *
     * @return the value of withdraw.state
     *
     * @mbggenerated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw.state
     *
     * @param state the value for withdraw.state
     *
     * @mbggenerated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw.withdraw_type
     *
     * @return the value of withdraw.withdraw_type
     *
     * @mbggenerated
     */
    public Integer getWithdrawType() {
        return withdrawType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw.withdraw_type
     *
     * @param withdrawType the value for withdraw.withdraw_type
     *
     * @mbggenerated
     */
    public void setWithdrawType(Integer withdrawType) {
        this.withdrawType = withdrawType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw.deal_persion
     *
     * @return the value of withdraw.deal_persion
     *
     * @mbggenerated
     */
    public String getDealPersion() {
        return dealPersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw.deal_persion
     *
     * @param dealPersion the value for withdraw.deal_persion
     *
     * @mbggenerated
     */
    public void setDealPersion(String dealPersion) {
        this.dealPersion = dealPersion == null ? null : dealPersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw.update_date
     *
     * @return the value of withdraw.update_date
     *
     * @mbggenerated
     */
    public Long getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw.update_date
     *
     * @param updateDate the value for withdraw.update_date
     *
     * @mbggenerated
     */
    public void setUpdateDate(Long updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column withdraw.is_delete
     *
     * @return the value of withdraw.is_delete
     *
     * @mbggenerated
     */
    public Integer getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column withdraw.is_delete
     *
     * @param isDelete the value for withdraw.is_delete
     *
     * @mbggenerated
     */
    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

	public String getPaymentAccount() {
		return paymentAccount;
	}

	public void setPaymentAccount(String paymentAccount) {
		this.paymentAccount = paymentAccount;
	}
}