package com.quxin.freshfun.dao;

import com.quxin.freshfun.model.GoodsSelectionPOJO;

public interface GoodsSelectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_selection
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_selection
     *
     * @mbggenerated
     */
    int insert(GoodsSelectionPOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_selection
     *
     * @mbggenerated
     */
    int insertSelective(GoodsSelectionPOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_selection
     *
     * @mbggenerated
     */
    GoodsSelectionPOJO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_selection
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsSelectionPOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_selection
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GoodsSelectionPOJO record);
    
    GoodsSelectionPOJO selectByGoodsId(Integer goodsId);
}