package com.quxin.freshfun.dao;

import com.quxin.freshfun.model.GoodsDeliveryTypePOJO;

public interface GoodsDeliveryTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_delivery_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_delivery_type
     *
     * @mbggenerated
     */
    int insert(GoodsDeliveryTypePOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_delivery_type
     *
     * @mbggenerated
     */
    int insertSelective(GoodsDeliveryTypePOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_delivery_type
     *
     * @mbggenerated
     */
    GoodsDeliveryTypePOJO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_delivery_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsDeliveryTypePOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_delivery_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GoodsDeliveryTypePOJO record);
    /**
     * 根据套餐编号查询套餐信息
     * @param deliveryId
     * @return
     */
    GoodsDeliveryTypePOJO selectByDeliveryId(Integer deliveryId);
}