package com.quxin.freshfun.dao;

import java.util.List;

import com.quxin.freshfun.model.GoodsTypePOJO;

public interface GoodsTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbggenerated
     */
    int insert(GoodsTypePOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbggenerated
     */
    int insertSelective(GoodsTypePOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbggenerated
     */
    GoodsTypePOJO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsTypePOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GoodsTypePOJO record);
    
    /**
     * 查询类别
     * @return
     */
    List<GoodsTypePOJO> findAll();
    
    /**
     * 通过类别查询
     * @return
     */
    List<GoodsTypePOJO> findByType(String goods_type);
    
    /**
     * 通过类别查询
     * @return
     */
    List<GoodsTypePOJO>findAllGoods();
}