package com.quxin.freshfun.dao;

import com.quxin.freshfun.model.GoodsDeliveryTimesPOJO;

public interface GoodsDeliveryTimesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_delivery_times
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_delivery_times
     *
     * @mbggenerated
     */
    int insert(GoodsDeliveryTimesPOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_delivery_times
     *
     * @mbggenerated
     */
    int insertSelective(GoodsDeliveryTimesPOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_delivery_times
     *
     * @mbggenerated
     */
    GoodsDeliveryTimesPOJO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_delivery_times
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsDeliveryTimesPOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_delivery_times
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GoodsDeliveryTimesPOJO record);
    /**
     * 根据类型编号查询发货次数
     * @param typeId
     * @return
     */
    GoodsDeliveryTimesPOJO selectByTypeId(int typeId);
    
}