package com.quxin.freshfun.dao;

import java.util.List;
import java.util.Map;

import com.quxin.freshfun.model.GoodsPOJO;

public interface GoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated
     */
    int insert(GoodsPOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated
     */
    int insertSelective(GoodsPOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated
     */
    GoodsPOJO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsPOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GoodsPOJO record);
    /**
     * 根据商品编号查询商户信息
     * @param goodsId
     * @return
     */
    GoodsPOJO selectMerchantByGoodsId(Integer goodsId);
    
    /**
     * 查询所有商品
     * @return
     */
    List<GoodsPOJO> findByLimit(Map<String, Integer> goodsMap);
    
    
    /**
     * 查询单个商品
     * @return
     */
    GoodsPOJO findByGoodsId(Integer goods_id);
    /**
     * 查询单个商品信息
     * @param goods_id
     * @return
     */
    GoodsPOJO selectGoodsById(Integer goods_id);
    /**
     * 根据商品编号查询代理商户信息
     * @param goodsId
     * @return
     */
    GoodsPOJO selectProxyMerchantByGoodsId(Integer goodsId);
    /**
     * 查询推荐商品
     * @return
     */
    List<GoodsPOJO> selectRecommendGoods();
    /**
     * 查询单个商品信息
     * @param goodsId
     * @return
     */
    GoodsPOJO selectShoppingInfo(Integer goodsId);
    /**
     * 查询类别查询精选大图
     * @param goodsId
     * @return
     */
    GoodsPOJO findByType(Integer goodsId);
}