package com.quxin.freshfun.dao;




import com.quxin.freshfun.model.GtypeVsGid;

public interface GtypeVsGidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gtype_vs_gid
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gtype_vs_gid
     *
     * @mbggenerated
     */
    int insert(GtypeVsGid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gtype_vs_gid
     *
     * @mbggenerated
     */
    int insertSelective(GtypeVsGid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gtype_vs_gid
     *
     * @mbggenerated
     */
    GtypeVsGid selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gtype_vs_gid
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GtypeVsGid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gtype_vs_gid
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GtypeVsGid record);
    
}