package com.quxin.freshfun.dao;

import com.quxin.freshfun.model.MerchantAgent;

public interface MerchantAgentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_agent
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_agent
     *
     * @mbggenerated
     */
    int insert(MerchantAgent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_agent
     *
     * @mbggenerated
     */
    int insertSelective(MerchantAgent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_agent
     *
     * @mbggenerated
     */
    MerchantAgent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_agent
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MerchantAgent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_agent
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MerchantAgent record);

    /**
     * 修改支付状态
     * @param id
     * @return
     */
    int updatePayStatus(int id);

    /**
     * 查询商户信息
     * @param id
     * @return
     */
    MerchantAgent selectMerchantInfo(Integer id);
}