package com.quxin.freshfun.dao;

import java.util.List;
import java.util.Map;

import com.quxin.freshfun.model.OrdersPOJO;

public interface OrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated
     */
    int insert(OrdersPOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated
     */
    int insertSelective(OrdersPOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated
     */
    OrdersPOJO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrdersPOJO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrdersPOJO record);
    
    /**
     * 查询所有订单
     * @return
     */
    List<OrdersPOJO> findAllOrders();
    /**
     * 根据用户编号分页查询订单信息
     * @param map
     * @return
     */
    List<OrdersPOJO> selectPagingByUserId(Map<String, Integer> map);
    /**
     * 删除订单信息
     * @param orderId
     * @return
     */
    int delOrderdelOrder(Integer orderId);
    /**
     * 修改订单状态为已支付
     * @param orderId
     * @return
     */
    int updateOrderPayStatus(Integer orderId);

    /**
     * 根据父级订单编号查询订单信息
     * @return
     */
    OrdersPOJO selectById(String orderId);
}