package com.quxin.freshfun.dao;

import java.util.List;
import java.util.Map;

import com.quxin.freshfun.model.SmidVsGid;

public interface SmidVsGidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smid_vs_gid
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smid_vs_gid
     *
     * @mbggenerated
     */
    int insert(SmidVsGid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smid_vs_gid
     *
     * @mbggenerated
     */
    int insertSelective(SmidVsGid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smid_vs_gid
     *
     * @mbggenerated
     */
    SmidVsGid selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smid_vs_gid
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SmidVsGid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smid_vs_gid
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmidVsGid record);
    
    List<SmidVsGid> selectGoodsLimit(Map<String, Integer> mallMap);
}