package com.quxin.freshfun.dao;

import java.util.List;

import com.quxin.freshfun.model.SpecialTheme;

public interface SpecialThemeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_theme
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_theme
     *
     * @mbggenerated
     */
    int insert(SpecialTheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_theme
     *
     * @mbggenerated
     */
    int insertSelective(SpecialTheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_theme
     *
     * @mbggenerated
     */
    SpecialTheme selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_theme
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SpecialTheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_theme
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SpecialTheme record);
    
    /**
     * 查询专题
     * @return
     */
    List<SpecialTheme> findAll();
}