package com.quxin.freshfun.dao;

import java.util.List;

import com.quxin.freshfun.model.SpecialMall;

public interface SpecialMallMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_mall
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_mall
     *
     * @mbggenerated
     */
    int insert(SpecialMall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_mall
     *
     * @mbggenerated
     */
    int insertSelective(SpecialMall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_mall
     *
     * @mbggenerated
     */
    SpecialMall selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_mall
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SpecialMall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_mall
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SpecialMall record);
    /**
     * 查询banner数据
     * @return
     */
    List<SpecialMall> findAll();
}