package com.quxin.freshfun.dao;

import com.quxin.freshfun.model.UserRevenueDetails;

public interface UserRevenueDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_revenue_details
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_revenue_details
     *
     * @mbggenerated
     */
    int insert(UserRevenueDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_revenue_details
     *
     * @mbggenerated
     */
    int insertSelective(UserRevenueDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_revenue_details
     *
     * @mbggenerated
     */
    UserRevenueDetails selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_revenue_details
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserRevenueDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_revenue_details
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserRevenueDetails record);
}