package com.quxin.freshfun.dao;

import java.util.List;

import com.quxin.freshfun.model.UserOutcome;

public interface UserOutcomeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_outcome
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_outcome
     *
     * @mbggenerated
     */
    int insert(UserOutcome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_outcome
     *
     * @mbggenerated
     */
    int insertSelective(UserOutcome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_outcome
     *
     * @mbggenerated
     */
    UserOutcome selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_outcome
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserOutcome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_outcome
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserOutcome record);
    /**
     * 根据用户查询支出账单
     * @param userId
     * @return
     */
    List<UserOutcome> selectOutcomeBill(Long userId);
}