package com.quxin.freshfun.dao;

import java.util.List;
import java.util.Map;

import com.quxin.freshfun.model.UserAddress;

public interface UserAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbggenerated
     */
    int insert(UserAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbggenerated
     */
    int insertSelective(UserAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbggenerated
     */
    UserAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserAddress record);
    
    List<UserAddress> selectAllByUserID(Long userID);

    /**
     * 获取用户默认地址
     * @param userID
     * @return
     */
    List<UserAddress> selectdefaultByUserID(Long userID);
    
    int insertNewAddress(Map<String, Object> addressMap);
    
    int updateIsDefault(Long userID);

    /**
     * 根据地址编号查询地址快照信息
     * @param addressId
     * @return
     */
    UserAddress selectAddressById(Integer addressId);
}