package com.quxin.freshfun.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import com.quxin.freshfun.model.Withdraw;

public interface WithdrawMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(@Param("id") Integer id, @Param("userId") Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw
     *
     * @mbggenerated
     */
    int insert(Withdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw
     *
     * @mbggenerated
     */
    int insertSelective(Withdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw
     *
     * @mbggenerated
     */
    Withdraw selectByPrimaryKey(@Param("id") Integer id, @Param("userId") Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Withdraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table withdraw
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Withdraw record);
    /**
     * 查询提现记录
     * @param userId
     * @return
     */
    List<Withdraw> selectPresentRecord(Long userId);
}